title:     SANSUI | BLOG
description: 三嵗的生活博客
baseurl: "/blog"
url:     https://buyivi.xyz
signoff:          "Xuny"
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: G-M6S7H99VS0

links:
  - name:         友邻
    url:          /blog/friend
  - name:         文章
    url:          /blog
  - name:         分类
    url:          /blog/categories
  - name:         标签
    url:          /blog/tags
  - name:         书单
    url:          /blog/books
  - name:         邮件
    url:          mailto:sansui_z@126.com
    external:     true
  - name:         主页
    url:          https://buyivi.xyz/
    external:     true

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
